language: python
python:
  - "2.7"
  - "3.3"
# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"
# command to run tests with code coverage
script: "coverage run -m unittest discover"
after_success: coveralls